login: &login
  adapter: postgresql
  username: nemot.org
  password: NewPass
  host: localhost
  port: 5433
  encoding: unicode

test:
  <<: *login
  database: nemot_test

production:
  <<: *login
  database: nemot_prod

staging:
  <<: *login
  database: nemot_prod

development:
  <<: *login
  database: nemot_prod

cucumber:
  <<: *login
  database: nemot_test
